comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        informational: true
    patch: off
# TODO: test 작성 시 patch 켜기